service: leancoffee

provider:
  name: aws
  runtime: nodejs8.10
  region: ${opt:region, 'eu-central-1'}
  stage: ${opt:stage, 'staging'}
functions:
  app:
    handler: 'src/server/index.handler'
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
plugins:
  - serverless-webpack
  - serverless-finch

custom:
  rootDomain: 'leancoff.ee'
  client:
    bucketName: ${self:provider.stage}.${self:custom.rootDomain}
    distributionFolder: 'src/client/dist'
    indexDocument: index.html
    errorDocument: index.html
  webpack:
    webpackConfig: 'src/server/config/webpack.config.js'
    includeModules: true

resources:
  Resources:
    FrontendBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.client.bucketName}
        AccessControl: Private
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html
    CloudfrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Aliases:
            Fn::Split: [",", "${opt:aliases}"]
          Comment: ${self:provider.stage} distribution
          HttpVersion: 'http2'
          Enabled: true
          DefaultRootObject: index.html
          CacheBehaviors:
          - TargetOriginId: api
            Compress: true
            PathPattern: "/api/*"
            ViewerProtocolPolicy: redirect-to-https
            MinTTL: 0
            AllowedMethods:
              - HEAD
              - DELETE
              - POST
              - GET
              - OPTIONS
              - PUT
              - PATCH
            CachedMethods:
              - HEAD
              - GET
            ForwardedValues:
              Cookies:
                Forward: all
              QueryString: true
          DefaultCacheBehavior:
            TargetOriginId: FrontendBucket
            ViewerProtocolPolicy: redirect-to-https
            MinTTL: 0
            AllowedMethods:
              - HEAD
              - GET
            CachedMethods:
              - HEAD
              - GET
            ForwardedValues:
              Cookies:
                Forward: none
              QueryString: false
          Origins:
            - DomainName:
                Fn::Select: [2, Fn::Split: ['/', Fn::GetAtt: FrontendBucket.WebsiteURL]]
              Id: FrontendBucket
              CustomOriginConfig:
                OriginProtocolPolicy: http-only
            - DomainName:
                Fn::Join:
                  - ''
                  - - Ref: ApiGatewayRestApi
                    - '.execute-api.${self:provider.region}.amazonaws.com'
              Id: api
              OriginPath: "/${self:provider.stage}"
              CustomOriginConfig:
                OriginProtocolPolicy: https-only
          ViewerCertificate:
            SslSupportMethod: sni-only
            MinimumProtocolVersion: TLSv1.1_2016
            AcmCertificateArn: 'arn:aws:acm:us-east-1:798037437596:certificate/c7271831-f420-454f-a1fb-72de52401a08'
    Domain:
      Type: AWS::Route53::RecordSetGroup
      Properties:
        HostedZoneName: ${self:custom.rootDomain}.
        RecordSets:
        - Name: ${self:provider.stage}.${self:custom.rootDomain}.
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName:
              "Fn::GetAtt": [ CloudfrontDistribution, DomainName ]
